resposta = input('Digite algo: ')
print('O tipo primitivo desse input é {}'.format(type(resposta)))
print('Só tem espaços em branco? {}'.format(resposta.isspace()))
print('É um número?', resposta.isnumeric())
print('É alfabético?', resposta.isalpha())
print('É alfanumérico?', resposta.isalnum())
print('Está em letras maiúsculas?', resposta.isupper())
print('Está em letras minúsculas?', resposta.islower())
print('Está com a Primeira Letra Maiúscula?', resposta.istitle())
