times = ('Atlético-MG', 'Flamengo', 'São Paulo', 'Internacional', 'Fluminense', 'Palmeiras', 'Santos', 'Grêmio', 'Athletico-PR', 'Bahia', 'Fortaleza', 'Atlético-GO', 'Bragantino', 'Corinthians', 'Sport', 'Ceará', 'Vasco', 'Coritiba', 'Botafogo', 'Goiás')

print('-=' * 15)
print(f'Lista de times do Brasileirão: {times}')
print('-=' * 15)
print(f'Os 5 primeiros são {times[0:5]}')
print('-=' * 15)
print(f'Os 4 últimos são {times[-4:]}')
print('-=' * 15)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 15)
print(f'A competição possui {len(times)} participantes')
print('-=' * 15)
print(f'O Coritiba está na {times.index("Coritiba") + 1}a posição')